#!/bin/bash
set -e

QB_HOME="/opt/quickbuild"
HIBERNATE_PROPS="${QB_HOME}/conf/hibernate.properties"

# Check if the configuration file still uses the default H2 database
if grep -q "hibernate.connection.driver_class=org.h2.Driver" "$HIBERNATE_PROPS" || [ ! -f "$HIBERNATE_PROPS" ]; then
    echo "Configuring hibernate.properties for PostgreSQL..."

    if [ -z "$DB_PASSWORD" ]; then
        echo "Error: DB_PASSWORD environment variable not set. Cannot configure database."
        exit 1
    fi

    # Create/Overwrite hibernate.properties with PostgreSQL settings
    cat > "$HIBERNATE_PROPS" <<EOF
# Auto-generated by Docker entrypoint script
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://${DB_HOST:-quickbuild-db}:${DB_PORT:-5432}/${DB_NAME:-quickbuild}
hibernate.connection.username=${DB_USER:-qbuser}
hibernate.connection.password=${DB_PASSWORD}
hibernate.c3p0.min_size=5
hibernate.c3p0.max_size=20
EOF
    echo "hibernate.properties configured for PostgreSQL."
else
    echo "hibernate.properties appears already configured. Skipping auto-configuration."
fi

# Execute the main command (e.g., "bin/server.sh console")
exec "$@"
